{
 "title": "市场交易",
 "time": { "from": "2025-12-20T12:39:16.101Z", "to": "2025-12-20T12:53:25.714Z" },
 "templating": {
  "list": [
   { "name": "task_id", "label": "任务名称", "query": "x8hFFu2Ice7fPaVt" }
  ]
 },
 "panels": [
  { "title": "成交-食物", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "成交量分析-食物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    COUNT(*) as trade_count\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Food'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "成交价变化曲线-食物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('1 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    AVG(price) AS price\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Food'\nGROUP BY date_bin('1 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "分商品贸易额变化曲线-食物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('1 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    sum(price) AS amount\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Food'\nGROUP BY date_bin('1 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "交易量分交易结果图表",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    COUNT(CASE WHEN trade_result = 'Success' THEN 1 END) as Success,\n    COUNT(CASE WHEN trade_result = 'Failed' THEN 1 END) as Failed,\n    COUNT(CASE WHEN trade_result = 'NotMatched' THEN 1 END) as NotMatched,\n    COUNT(CASE WHEN trade_result = 'NotYet' THEN 1 END) as NotYet,\nFROM public.trade_logs \nWHERE  task_id = '${task_id}' AND product_category = 'Food'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),product_id;\n"
    }
   ]
  },
  {
   "title": "交易失败原因细分类",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    COUNT(CASE WHEN interval_relation = 'Overlapping' THEN 1 END) as Over_lapping,\n    COUNT(CASE WHEN interval_relation = 'AgentBelowFactory' THEN 1 END) as Agent_Below_Factory,\n    COUNT(CASE WHEN interval_relation = 'AgentAboveFactory' THEN 1 END) as Agent_Above_Factory,\nFROM public.trade_logs \nWHERE  task_id = '${task_id}' AND product_category = 'Food'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp)\n"
    }
   ]
  },
  { "title": "成交-饮用水", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "成交量分析-水",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    COUNT(*) as trade_count\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Water'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "成交价变化曲线-水",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('1 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    AVG(price) AS price\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Water'\nGROUP BY date_bin('1 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "分商品贸易额变化曲线-水",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('1 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    sum(price) AS amount\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Water'\nGROUP BY date_bin('1 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "交易量分交易结果图表",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    COUNT(CASE WHEN trade_result = 'Success' THEN 1 END) as Success,\n    COUNT(CASE WHEN trade_result = 'Failed' THEN 1 END) as Failed,\n    COUNT(CASE WHEN trade_result = 'NotMatched' THEN 1 END) as NotMatched,\n    COUNT(CASE WHEN trade_result = 'NotYet' THEN 1 END) as NotYet,\nFROM public.trade_logs \nWHERE  task_id = '${task_id}' AND product_category = 'Water'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),product_id;\n"
    }
   ]
  },
  {
   "title": "交易失败原因细分类",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    COUNT(CASE WHEN interval_relation = 'Overlapping' THEN 1 END) as Over_lapping,\n    COUNT(CASE WHEN interval_relation = 'AgentBelowFactory' THEN 1 END) as Agent_Below_Factory,\n    COUNT(CASE WHEN interval_relation = 'AgentAboveFactory' THEN 1 END) as Agent_Above_Factory,\nFROM public.trade_logs \nWHERE  task_id = '${task_id}' AND product_category = 'Water'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp)\n"
    }
   ]
  },
  { "title": "成交-衣服", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "成交量分析-衣服",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    COUNT(*) as trade_count\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Clothing'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "成交价变化曲线-衣服",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('1 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    AVG(price) AS price\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Clothing'\nGROUP BY date_bin('1 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "分商品贸易额变化曲线-衣服",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('1 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    sum(price) AS amount\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Clothing'\nGROUP BY date_bin('1 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "交易量分交易结果图表",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    COUNT(CASE WHEN trade_result = 'Success' THEN 1 END) as Success,\n    COUNT(CASE WHEN trade_result = 'Failed' THEN 1 END) as Failed,\n    COUNT(CASE WHEN trade_result = 'NotMatched' THEN 1 END) as NotMatched,\n    COUNT(CASE WHEN trade_result = 'NotYet' THEN 1 END) as NotYet,\nFROM public.trade_logs \nWHERE  task_id = '${task_id}' AND product_category = 'Clothing'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),product_id;\n"
    }
   ]
  },
  {
   "title": "交易失败原因细分类",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    COUNT(CASE WHEN interval_relation = 'Overlapping' THEN 1 END) as Over_lapping,\n    COUNT(CASE WHEN interval_relation = 'AgentBelowFactory' THEN 1 END) as Agent_Below_Factory,\n    COUNT(CASE WHEN interval_relation = 'AgentAboveFactory' THEN 1 END) as Agent_Above_Factory,\nFROM public.trade_logs \nWHERE  task_id = '${task_id}' AND product_category = 'Clothing'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp)\n"
    }
   ]
  },
  { "title": "成交-交通", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "成交量分析-交通",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    COUNT(*) as trade_count\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Transport'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "成交价变化曲线-交通",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('1 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    AVG(price) AS price\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Transport'\nGROUP BY date_bin('1 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "分商品贸易额变化曲线-交通",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('1 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    sum(price) AS amount\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Transport'\nGROUP BY date_bin('1 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "交易量分交易结果图表",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    COUNT(CASE WHEN trade_result = 'Success' THEN 1 END) as Success,\n    COUNT(CASE WHEN trade_result = 'Failed' THEN 1 END) as Failed,\n    COUNT(CASE WHEN trade_result = 'NotMatched' THEN 1 END) as NotMatched,\n    COUNT(CASE WHEN trade_result = 'NotYet' THEN 1 END) as NotYet,\nFROM public.trade_logs \nWHERE  task_id = '${task_id}' AND product_category = 'Transport'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),product_id;\n"
    }
   ]
  },
  {
   "title": "交易失败原因细分类",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    COUNT(CASE WHEN interval_relation = 'Overlapping' THEN 1 END) as Over_lapping,\n    COUNT(CASE WHEN interval_relation = 'AgentBelowFactory' THEN 1 END) as Agent_Below_Factory,\n    COUNT(CASE WHEN interval_relation = 'AgentAboveFactory' THEN 1 END) as Agent_Above_Factory,\nFROM public.trade_logs \nWHERE  task_id = '${task_id}' AND product_category = 'Transport'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp)\n"
    }
   ]
  },
  { "title": "成交-娱乐", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "成交量分析-娱乐",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    COUNT(*) as trade_count\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Entertainment'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "成交价变化曲线-娱乐",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('1 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    AVG(price) AS price\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Entertainment'\nGROUP BY date_bin('1 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "分商品贸易额变化曲线-交通",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('1 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    sum(price) AS amount\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Entertainment'\nGROUP BY date_bin('1 seconds'::INTERVAL, timestamp),product_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "交易量分交易结果图表",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    product_id,\n    COUNT(CASE WHEN trade_result = 'Success' THEN 1 END) as Success,\n    COUNT(CASE WHEN trade_result = 'Failed' THEN 1 END) as Failed,\n    COUNT(CASE WHEN trade_result = 'NotMatched' THEN 1 END) as NotMatched,\n    COUNT(CASE WHEN trade_result = 'NotYet' THEN 1 END) as NotYet,\nFROM public.trade_logs \nWHERE  task_id = '${task_id}' AND product_category = 'Entertainment'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),product_id;\n"
    }
   ]
  },
  {
   "title": "交易失败原因细分类",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    COUNT(CASE WHEN interval_relation = 'Overlapping' THEN 1 END) as Over_lapping,\n    COUNT(CASE WHEN interval_relation = 'AgentBelowFactory' THEN 1 END) as Agent_Below_Factory,\n    COUNT(CASE WHEN interval_relation = 'AgentAboveFactory' THEN 1 END) as Agent_Above_Factory,\nFROM public.trade_logs \nWHERE  task_id = '${task_id}' AND product_category = 'Entertainment'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp)\n"
    }
   ]
  },
  { "title": "商家-食物", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "商家心理区间变化趋势-食物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 86 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    factory_id,\n    avg(factory_supply_range_upper) as upper,\n    avg(factory_supply_range_lower) as lower\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Food'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),factory_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "商家的区间调整预期-食物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 86 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  date_bin('2 seconds' :: INTERVAL, timestamp) as time_window,\n  avg(lower_change) as lower_change,\n  avg(upper_change) AS upper_change\nFROM\n  factory_range_optimization_logs\nwhere\n  task_id = '${task_id}'\n  AND product_category = 'Food'\nGROUP BY\n  date_bin('2 seconds' :: INTERVAL, timestamp);"
    }
   ]
  },
  {
   "title": "商家总剩余资金-食物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  sum(cash) as cash\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}'\n  AND product_category = 'Food'\nGROUP BY\n  `timestamp`;"
    }
   ]
  },
  {
   "title": "分商家剩余资金曲线-食物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  factory_id,\n  cash as cash\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}'\n  AND product_category = 'Food'\n  ;"
    }
   ]
  },
  {
   "title": "商家产量以及剩余库存量-食物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 102 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  sum(initial_stock) as initial_stock,\n  sum(remaining_stock) as remaining_stock\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}' and product_category = 'Food'\nGROUP BY\n  `timestamp`;"
    }
   ]
  },
  {
   "title": "分组商家产量以及剩余库存量-食物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 102 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  date_bin('3 seconds' :: INTERVAL, timestamp) as time_window,\n  factory_id,\n  sum(initial_stock) as initial_stock,\n  sum(remaining_stock) as remaining_stock\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}' AND product_category = 'Food'\nGROUP BY\n  date_bin('3 seconds'::INTERVAL, timestamp),\n  factory_id;"
    }
   ]
  },
  { "title": "商家-饮用水", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "商家心理区间变化趋势-饮用水",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 111 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    factory_id,\n    avg(factory_supply_range_upper) as upper,\n    avg(factory_supply_range_lower) as lower\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Water'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),factory_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "商家的区间调整预期-饮用水",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 111 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  date_bin('2 seconds' :: INTERVAL, timestamp) as time_window,\n  avg(lower_change) as lower_change,\n  avg(upper_change) AS upper_change\nFROM\n  factory_range_optimization_logs\nwhere\n  task_id = '${task_id}'\n  AND product_category = 'Water'\nGROUP BY\n  date_bin('2 seconds' :: INTERVAL, timestamp);"
    }
   ]
  },
  {
   "title": "商家总剩余资金-饮用水",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  sum(cash) as cash\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}'\n  AND product_category = 'Water'\nGROUP BY\n  `timestamp`;"
    }
   ]
  },
  {
   "title": "分商家剩余资金曲线-引用水",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  factory_id,\n  cash as cash\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}'\n  AND product_category = 'Water'\n  ;"
    }
   ]
  },
  {
   "title": "商家产量以及剩余库存量-饮用水",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 127 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  sum(initial_stock) as initial_stock,\n  sum(remaining_stock) as remaining_stock\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}' and product_category = 'Water'\nGROUP BY\n  `timestamp`;"
    }
   ]
  },
  {
   "title": "分组商家产量以及剩余库存量-水",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 127 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  date_bin('3 seconds' :: INTERVAL, timestamp) as time_window,\n  factory_id,\n  sum(initial_stock) as initial_stock,\n  sum(remaining_stock) as remaining_stock\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}' AND product_category = 'Water'\nGROUP BY\n  date_bin('3 seconds'::INTERVAL, timestamp),\n  factory_id;"
    }
   ]
  },
  { "title": "商家-衣服", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "title": "商家心理区间变化趋势-衣服",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 136 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    factory_id,\n    avg(factory_supply_range_upper) as upper,\n    avg(factory_supply_range_lower) as lower\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Clothing'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),factory_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "商家的区间调整预期-衣物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 136 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  date_bin('2 seconds' :: INTERVAL, timestamp) as time_window,\n  avg(lower_change) as lower_change,\n  avg(upper_change) AS upper_change\nFROM\n  factory_range_optimization_logs\nwhere\n  task_id = '${task_id}'\n  AND product_category = 'Clothing'\nGROUP BY\n  date_bin('2 seconds' :: INTERVAL, timestamp);"
    }
   ]
  },
  {
   "title": "商家总剩余资金-衣物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  sum(cash) as cash\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}'\n  AND product_category = 'Clothing'\nGROUP BY\n  `timestamp`;"
    }
   ]
  },
  {
   "title": "分商家剩余资金曲线-衣物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  factory_id,\n  cash as cash\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}'\n  AND product_category = 'Clothing'\n  ;"
    }
   ]
  },
  {
   "title": "商家产量以及剩余库存量-衣物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 152 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  sum(initial_stock) as initial_stock,\n  sum(remaining_stock) as remaining_stock\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}' and product_category = 'Clothing'\nGROUP BY\n  `timestamp`;"
    }
   ]
  },
  {
   "title": "分组商家产量以及剩余库存量-衣物",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 152 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  date_bin('3 seconds' :: INTERVAL, timestamp) as time_window,\n  factory_id,\n  sum(initial_stock) as initial_stock,\n  sum(remaining_stock) as remaining_stock\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}' AND product_category = 'Clothing'\nGROUP BY\n  date_bin('3 seconds'::INTERVAL, timestamp),\n  factory_id;"
    }
   ]
  },
  { "title": "商家-交通", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  {
   "title": "商家心理区间变化趋势-交通",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 161 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    factory_id,\n    avg(factory_supply_range_upper) as upper,\n    avg(factory_supply_range_lower) as lower\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Transport'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),factory_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "商家的区间调整预期-交通",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 161 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  date_bin('2 seconds' :: INTERVAL, timestamp) as time_window,\n  avg(lower_change) as lower_change,\n  avg(upper_change) AS upper_change\nFROM\n  factory_range_optimization_logs\nwhere\n  task_id = '${task_id}'\n  AND product_category = 'Transport'\nGROUP BY\n  date_bin('2 seconds' :: INTERVAL, timestamp);"
    }
   ]
  },
  {
   "title": "商家总剩余资金-交通",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  sum(cash) as cash\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}'\n  AND product_category = 'Transport'\nGROUP BY\n  `timestamp`;"
    }
   ]
  },
  {
   "title": "分商家剩余资金曲线-交通",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  factory_id,\n  cash as cash\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}'\n  AND product_category = 'Transport'\n  ;"
    }
   ]
  },
  {
   "title": "商家产量以及剩余库存量-交通",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 177 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  sum(initial_stock) as initial_stock,\n  sum(remaining_stock) as remaining_stock\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}' and product_category = 'Transport'\nGROUP BY\n  `timestamp`;"
    }
   ]
  },
  {
   "title": "分组商家产量以及剩余库存量-交通",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 177 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  date_bin('3 seconds' :: INTERVAL, timestamp) as time_window,\n  factory_id,\n  sum(initial_stock) as initial_stock,\n  sum(remaining_stock) as remaining_stock\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}' AND product_category = 'Transport'\nGROUP BY\n  date_bin('3 seconds'::INTERVAL, timestamp),\n  factory_id;"
    }
   ]
  },
  { "title": "商家-娱乐", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 185 } },
  {
   "title": "商家心理区间变化趋势-娱乐",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 186 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    factory_id,\n    avg(factory_supply_range_upper) as upper,\n    avg(factory_supply_range_lower) as lower\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\n    AND product_category = 'Entertainment'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp),factory_id\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "商家的区间调整预期-娱乐",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 186 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  date_bin('2 seconds' :: INTERVAL, timestamp) as time_window,\n  avg(lower_change) as lower_change,\n  avg(upper_change) AS upper_change\nFROM\n  factory_range_optimization_logs\nwhere\n  task_id = '${task_id}'\n  AND product_category = 'Entertainment'\nGROUP BY\n  date_bin('2 seconds' :: INTERVAL, timestamp);"
    }
   ]
  },
  {
   "title": "商家总剩余资金-娱乐",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  sum(cash) as cash\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}'\n  AND product_category = 'Entertainment'\nGROUP BY\n  `timestamp`;"
    }
   ]
  },
  {
   "title": "分商家剩余资金曲线-娱乐",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  factory_id,\n  cash as cash\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}'\n  AND product_category = 'Entertainment'\n  ;"
    }
   ]
  },
  {
   "title": "商家产量以及剩余库存量-娱乐",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 202 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  `timestamp`,\n  sum(initial_stock) as initial_stock,\n  sum(remaining_stock) as remaining_stock\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}' and product_category = 'Entertainment'\nGROUP BY\n  `timestamp`;"
    }
   ]
  },
  {
   "title": "分组商家产量以及剩余库存量-娱乐",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 202 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT\n  date_bin('3 seconds' :: INTERVAL, timestamp) as time_window,\n  factory_id,\n  sum(initial_stock) as initial_stock,\n  sum(remaining_stock) as remaining_stock\nFROM\n  public.factory_end_of_round_logs\nWHERE\n  task_id = '${task_id}' AND product_category = 'Entertainment'\nGROUP BY\n  date_bin('3 seconds'::INTERVAL, timestamp),\n  factory_id;"
    }
   ]
  },
  { "title": "消费者", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 210 } },
  {
   "title": "消费者心理曲线",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 211 },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('2 seconds'::INTERVAL, timestamp) as time_window,\n    avg(agent_pref_current_range_upper) as max_upper,\n    avg(agent_pref_current_range_lower) AS min_lower\nFROM public.trade_logs \nWHERE price > 0.0 \n    AND task_id = '${task_id}'\nGROUP BY date_bin('2 seconds'::INTERVAL, timestamp)\nORDER BY time_window"
    }
   ]
  },
  {
   "title": "消费者心理预期调整趋势",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT date_bin('2 seconds'::INTERVAL, timestamp) as time_window,avg(lower_change) as lower_change, avg(upper_change) AS upper_change FROM agent_range_adjustment_logs where task_id = '${task_id}' GROUP BY  date_bin('2 seconds'::INTERVAL, timestamp);"
    }
   ]
  },
  {
   "title": "消费者剩余资金",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    timestamp,\n    sum(cash)\nFROM public.agent_cash_logs \nWHERE  task_id = '${task_id}'\nGROUP BY timestamp;"
    }
   ]
  },
  {
   "title": "分消费者剩余资金",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "dataset": "public",
     "rawSql": "SELECT \n    date_bin('3 seconds' :: INTERVAL, timestamp) as time_window,\n    sum(cash) as cash,\n    agent_id\nFROM public.agent_cash_logs \nWHERE  task_id = '${task_id}'\nGROUP BY date_bin('3 seconds' :: INTERVAL, timestamp),agent_id;"
    }
   ]
  }
 ]
}